import {
  APP_CATALOG,
  getShopifyAppStoreUrl,
  type AppCatalogEntry,
} from "@/lib/constants/app-catalog";

export interface AppListingSeed {
  slug: string;
  name: string;
  listTitle: string;
  developerName: string;
  category: string;
  description: string;
  pricingLabel: string | null;
  rating: number | null;
  reviewCount: number | null;
  rankingBadge: string | null;
  iconUrl: string | null;
  appStoreSlug: string;
  sortOrder: number;
}

const LISTING_DESCRIPTIONS: Record<string, string> = {
  klaviyo:
    "Email and SMS marketing automation built for ecommerce — flows, segments, and revenue attribution.",
  "judge-me":
    "Collect and showcase product reviews with photos, Q&A, and trust badges that lift conversion.",
  loox: "Visual reviews with customer photos and videos — social proof on product pages.",
  attentive:
    "AI-led SMS and email marketing with high deliverability and lifecycle messaging.",
  aftership:
    "Branded shipment tracking, delivery updates, and post-purchase experiences.",
  omnisend:
    "Omnichannel campaigns across email, SMS, and push for growing Shopify brands.",
  yotpo: "Reviews, loyalty, and UGC tools for retention and social proof at scale.",
  rebuy: "AI-powered upsells, cross-sells, and cart merchandising personalization.",
  nosto: "AI search, merchandising, and product recommendations for discovery.",
  gorgias: "AI helpdesk, live chat, and support automation tied to Shopify orders.",
  bazaarvoice: "Enterprise reviews and syndicated UGC for established brands.",
  smile: "Loyalty points, referrals, and VIP tiers to increase repeat purchases.",
  privy: "Pop-ups, email capture, and conversion campaigns for list growth.",
  pagefly: "Drag-and-drop landing pages and sections without coding.",
  shogun: "Visual page builder for landing pages, product pages, and A/B tests.",
  recharge: "Subscriptions and recurring billing for membership commerce.",
  "zipify-pages": "High-converting landing pages and sales funnels for paid traffic.",
  route: "Package protection and carbon-neutral shipping offers at checkout.",
  tidio: "Live chat, chatbots, and multichannel inbox for support and sales.",
  pushowl: "Web push notifications to recover carts and announce launches.",
  stamped: "Reviews and loyalty with NPS surveys and Instagram UGC.",
  okendo: "Customer marketing platform with quizzes, reviews, and surveys.",
  "reviews-io": "Product and company reviews with Google Seller Ratings.",
  searchanise: "Fast AJAX search, filters, and merchandising for large catalogs.",
  vitals: "All-in-one conversion bundle — reviews, upsells, bundles, and more.",
  tiktok: "TikTok Shop and catalog sync for social commerce growth.",
  "facebook-channel": "Facebook and Instagram Shops catalog integration.",
  "google-youtube": "Google Merchant Center and YouTube Shopping listings.",
  pandectes: "GDPR and privacy compliance banners and consent management.",
  crushpics: "Image compression and SEO alt-text automation for speed.",
  bold: "Bold Subscriptions and custom pricing for recurring revenue.",
  tapcart: "Native mobile app builder for push, loyalty, and retention.",
  mailchimp: "Email marketing sync between Shopify and Mailchimp audiences.",
  shipbob: "Fulfillment network integration for 2-day shipping promises.",
  skio: "Subscriptions with passwordless login and churn reduction tools.",
  loyoly: "Loyalty, referrals, and ambassador programs for DTC brands.",
  heatmap: "Session recordings and heatmaps to optimize storefront UX.",
  hotjar: "Surveys, feedback, and behavior analytics on Shopify stores.",
  segment: "Customer data platform events for analytics and personalization.",
};

function catalogToListing(entry: AppCatalogEntry, sortOrder: number): AppListingSeed {
  const shortName =
    entry.slug === "judge-me"
      ? "Judge.me"
      : entry.slug === "zipify-pages"
        ? "Zipify"
        : entry.developerName.split(" ")[0] === entry.developerName
          ? entry.developerName
          : entry.matchNames[0].charAt(0).toUpperCase() + entry.matchNames[0].slice(1);

  return {
    slug: entry.slug,
    name: shortName,
    listTitle: entry.listTitle,
    developerName: entry.developerName,
    category: entry.category,
    description:
      LISTING_DESCRIPTIONS[entry.slug] ??
      `${entry.category} app for Shopify merchants.`,
    pricingLabel: entry.pricingLabel,
    rating: entry.rating,
    reviewCount: entry.reviewCount,
    rankingBadge: entry.rankingBadge,
    iconUrl: entry.iconUrl,
    appStoreSlug: entry.appStoreSlug,
    sortOrder,
  };
}

const listingOnlyApps: AppListingSeed[] = [
  {
    slug: "smile",
    name: "Smile",
    listTitle: "Smile: Rewards & Loyalty",
    developerName: "Smile.io",
    category: "Loyalty",
    description: LISTING_DESCRIPTIONS.smile,
    pricingLabel: "Free plan available",
    rating: 4.9,
    reviewCount: 4000,
    rankingBadge: "Top 50",
    iconUrl: null,
    appStoreSlug: "smile-io",
    sortOrder: 20,
  },
  {
    slug: "privy",
    name: "Privy",
    listTitle: "Privy Pop Ups, Email, & SMS",
    developerName: "Privy",
    category: "Pop-ups",
    description: LISTING_DESCRIPTIONS.privy,
    pricingLabel: "Free plan available",
    rating: 4.6,
    reviewCount: 3000,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "privy",
    sortOrder: 21,
  },
  {
    slug: "pagefly",
    name: "PageFly",
    listTitle: "PageFly Landing Page Builder",
    developerName: "PageFly",
    category: "Page Builder",
    description: LISTING_DESCRIPTIONS.pagefly,
    pricingLabel: "Free plan available",
    rating: 4.9,
    reviewCount: 6000,
    rankingBadge: "Top 50",
    iconUrl: null,
    appStoreSlug: "pagefly",
    sortOrder: 22,
  },
  {
    slug: "shogun",
    name: "Shogun",
    listTitle: "Shogun Landing Page Builder",
    developerName: "Shogun",
    category: "Page Builder",
    description: LISTING_DESCRIPTIONS.shogun,
    pricingLabel: "Free trial available",
    rating: 4.7,
    reviewCount: 800,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "shogun",
    sortOrder: 23,
  },
  {
    slug: "recharge",
    name: "Recharge",
    listTitle: "Recharge Subscriptions",
    developerName: "Recharge",
    category: "Subscriptions",
    description: LISTING_DESCRIPTIONS.recharge,
    pricingLabel: "Free trial available",
    rating: 4.2,
    reviewCount: 200,
    rankingBadge: "Top 100",
    iconUrl: null,
    appStoreSlug: "recharge",
    sortOrder: 24,
  },
  {
    slug: "zipify-pages",
    name: "Zipify",
    listTitle: "Zipify Pages",
    developerName: "Zipify Apps",
    category: "Page Builder",
    description: LISTING_DESCRIPTIONS["zipify-pages"],
    pricingLabel: "Free trial available",
    rating: 4.8,
    reviewCount: 400,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "zipify-pages",
    sortOrder: 25,
  },
  {
    slug: "route",
    name: "Route",
    listTitle: "Route Protection & Tracking",
    developerName: "Route",
    category: "Shipping",
    description: LISTING_DESCRIPTIONS.route,
    pricingLabel: "Free to install",
    rating: 4.5,
    reviewCount: 300,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "route",
    sortOrder: 26,
  },
  {
    slug: "tidio",
    name: "Tidio",
    listTitle: "Tidio Live Chat & AI",
    developerName: "Tidio",
    category: "Support",
    description: LISTING_DESCRIPTIONS.tidio,
    pricingLabel: "Free plan available",
    rating: 4.7,
    reviewCount: 1200,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "tidio-chat",
    sortOrder: 27,
  },
  {
    slug: "pushowl",
    name: "PushOwl",
    listTitle: "PushOwl Web Push Notifications",
    developerName: "PushOwl",
    category: "Marketing",
    description: LISTING_DESCRIPTIONS.pushowl,
    pricingLabel: "Free plan available",
    rating: 4.6,
    reviewCount: 900,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "pushowl",
    sortOrder: 28,
  },
  {
    slug: "stamped",
    name: "Stamped",
    listTitle: "Stamped.io Reviews & UGC",
    developerName: "Stamped.io",
    category: "Reviews",
    description: LISTING_DESCRIPTIONS.stamped,
    pricingLabel: "Free trial available",
    rating: 4.7,
    reviewCount: 1500,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "stamped-io",
    sortOrder: 29,
  },
  {
    slug: "okendo",
    name: "Okendo",
    listTitle: "Okendo Reviews & Quizzes",
    developerName: "Okendo",
    category: "Reviews",
    description: LISTING_DESCRIPTIONS.okendo,
    pricingLabel: "Free trial available",
    rating: 4.9,
    reviewCount: 200,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "okendo",
    sortOrder: 30,
  },
  {
    slug: "reviews-io",
    name: "Reviews.io",
    listTitle: "Reviews.io Product Reviews",
    developerName: "Reviews.io",
    category: "Reviews",
    description: LISTING_DESCRIPTIONS["reviews-io"],
    pricingLabel: "Free trial available",
    rating: 4.8,
    reviewCount: 350,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "reviews-io",
    sortOrder: 31,
  },
  {
    slug: "searchanise",
    name: "Searchanise",
    listTitle: "Searchanise Search & Filter",
    developerName: "Searchanise",
    category: "Search",
    description: LISTING_DESCRIPTIONS.searchanise,
    pricingLabel: "Free trial available",
    rating: 4.8,
    reviewCount: 600,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "searchanise",
    sortOrder: 32,
  },
  {
    slug: "vitals",
    name: "Vitals",
    listTitle: "Vitals: Reviews, Bundles & More",
    developerName: "Vitals",
    category: "Conversion",
    description: LISTING_DESCRIPTIONS.vitals,
    pricingLabel: "Free trial available",
    rating: 4.8,
    reviewCount: 2000,
    rankingBadge: "Top 100",
    iconUrl: null,
    appStoreSlug: "vitals",
    sortOrder: 33,
  },
  {
    slug: "tiktok",
    name: "TikTok",
    listTitle: "TikTok Shop & Catalog",
    developerName: "TikTok",
    category: "Sales Channels",
    description: LISTING_DESCRIPTIONS.tiktok,
    pricingLabel: "Free to install",
    rating: 4.4,
    reviewCount: 500,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "tiktok",
    sortOrder: 34,
  },
  {
    slug: "facebook-channel",
    name: "Facebook",
    listTitle: "Facebook & Instagram",
    developerName: "Meta",
    category: "Sales Channels",
    description: LISTING_DESCRIPTIONS["facebook-channel"],
    pricingLabel: "Free to install",
    rating: 4.3,
    reviewCount: 2000,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "facebook",
    sortOrder: 35,
  },
  {
    slug: "google-youtube",
    name: "Google",
    listTitle: "Google & YouTube",
    developerName: "Google",
    category: "Sales Channels",
    description: LISTING_DESCRIPTIONS["google-youtube"],
    pricingLabel: "Free to install",
    rating: 4.2,
    reviewCount: 1500,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "google",
    sortOrder: 36,
  },
  {
    slug: "pandectes",
    name: "Pandectes",
    listTitle: "Pandectes GDPR Compliance",
    developerName: "Pandectes",
    category: "Legal",
    description: LISTING_DESCRIPTIONS.pandectes,
    pricingLabel: "Free plan available",
    rating: 4.9,
    reviewCount: 800,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "pandectes-gdpr",
    sortOrder: 37,
  },
  {
    slug: "crushpics",
    name: "Crush.pics",
    listTitle: "Crush.pics Image Optimizer",
    developerName: "Crush.pics",
    category: "Store Optimization",
    description: LISTING_DESCRIPTIONS.crushpics,
    pricingLabel: "Free plan available",
    rating: 4.7,
    reviewCount: 400,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "crush-pics",
    sortOrder: 38,
  },
  {
    slug: "bold",
    name: "Bold",
    listTitle: "Bold Subscriptions",
    developerName: "Bold",
    category: "Subscriptions",
    description: LISTING_DESCRIPTIONS.bold,
    pricingLabel: "Free trial available",
    rating: 4.1,
    reviewCount: 300,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "bold-subscriptions",
    sortOrder: 39,
  },
  {
    slug: "tapcart",
    name: "Tapcart",
    listTitle: "Tapcart Mobile App",
    developerName: "Tapcart",
    category: "Mobile",
    description: LISTING_DESCRIPTIONS.tapcart,
    pricingLabel: "Free trial available",
    rating: 4.5,
    reviewCount: 150,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "tapcart",
    sortOrder: 40,
  },
  {
    slug: "mailchimp",
    name: "Mailchimp",
    listTitle: "Mailchimp Email & SMS",
    developerName: "Mailchimp",
    category: "Email Marketing",
    description: LISTING_DESCRIPTIONS.mailchimp,
    pricingLabel: "Free plan available",
    rating: 4.4,
    reviewCount: 700,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "mailchimp",
    sortOrder: 41,
  },
  {
    slug: "shipbob",
    name: "ShipBob",
    listTitle: "ShipBob Fulfillment",
    developerName: "ShipBob",
    category: "Fulfillment",
    description: LISTING_DESCRIPTIONS.shipbob,
    pricingLabel: "Free to install",
    rating: 4.3,
    reviewCount: 80,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "shipbob-fulfillment",
    sortOrder: 42,
  },
  {
    slug: "skio",
    name: "Skio",
    listTitle: "Skio Subscriptions",
    developerName: "Skio",
    category: "Subscriptions",
    description: LISTING_DESCRIPTIONS.skio,
    pricingLabel: "Free trial available",
    rating: 4.9,
    reviewCount: 120,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "skio",
    sortOrder: 43,
  },
  {
    slug: "loyoly",
    name: "Loyoly",
    listTitle: "Loyoly Loyalty & Referrals",
    developerName: "Loyoly",
    category: "Loyalty",
    description: LISTING_DESCRIPTIONS.loyoly,
    pricingLabel: "Free plan available",
    rating: 4.8,
    reviewCount: 90,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "loyoly",
    sortOrder: 44,
  },
  {
    slug: "hotjar",
    name: "Hotjar",
    listTitle: "Hotjar Heatmaps & Surveys",
    developerName: "Hotjar",
    category: "Analytics",
    description: LISTING_DESCRIPTIONS.hotjar,
    pricingLabel: "Free plan available",
    rating: 4.5,
    reviewCount: 200,
    rankingBadge: null,
    iconUrl: null,
    appStoreSlug: "hotjar",
    sortOrder: 45,
  },
];

const fromCatalog = APP_CATALOG.map((entry, i) =>
  catalogToListing(entry, i + 1)
);

const bySlug = new Map<string, AppListingSeed>();
for (const app of [...fromCatalog, ...listingOnlyApps]) {
  bySlug.set(app.slug, app);
}

export const appListingCatalog: AppListingSeed[] = [...bySlug.values()].sort(
  (a, b) => a.sortOrder - b.sortOrder
);

export function appListingToFeaturedShape(app: AppListingSeed) {
  return {
    slug: app.slug,
    name: app.name,
    listTitle: app.listTitle,
    developerName: app.developerName,
    category: app.category,
    description: app.description,
    pricingLabel: app.pricingLabel,
    rating: app.rating,
    reviewCount: app.reviewCount,
    rankingBadge: app.rankingBadge,
    iconUrl: app.iconUrl ?? "",
    shopifyAppStoreUrl: getShopifyAppStoreUrl(app.appStoreSlug),
  };
}
