import type { ThemePriceType } from "@/lib/constants/featured-themes";
import { featuredThemes } from "@/lib/constants/featured-themes";

export interface ThemeCatalogSeed {
  name: string;
  slug: string;
  vendor: string;
  description: string;
  priceType: ThemePriceType;
  priceLabel: string;
  themeStoreUrl: string;
  imageUrl: string | null;
  imageAlt: string;
  sortOrder: number;
}

const extraThemes: ThemeCatalogSeed[] = [
  {
    name: "Expanse",
    slug: "expanse",
    vendor: "Archetype Themes",
    description: "Versatile premium theme for large catalogs and multi-collection stores.",
    priceType: "premium",
    priceLabel: "Premium",
    themeStoreUrl: "https://themes.shopify.com/themes/expanse",
    imageUrl: null,
    imageAlt: "Expanse Shopify theme preview",
    sortOrder: 10,
  },
  {
    name: "Symmetry",
    slug: "symmetry",
    vendor: "Clean Canvas",
    description: "Balanced layouts for fashion and home brands with strong collection pages.",
    priceType: "premium",
    priceLabel: "Premium",
    themeStoreUrl: "https://themes.shopify.com/themes/symmetry",
    imageUrl: null,
    imageAlt: "Symmetry Shopify theme preview",
    sortOrder: 11,
  },
  {
    name: "Warehouse",
    slug: "warehouse",
    vendor: "Maestrooo",
    description: "Industrial-inspired theme suited to home, hardware, and maker brands.",
    priceType: "premium",
    priceLabel: "Premium",
    themeStoreUrl: "https://themes.shopify.com/themes/warehouse",
    imageUrl: null,
    imageAlt: "Warehouse Shopify theme preview",
    sortOrder: 12,
  },
  {
    name: "Debut",
    slug: "debut",
    vendor: "Shopify",
    description: "Classic free Shopify theme — a longtime starter choice for new merchants.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/debut",
    imageUrl: null,
    imageAlt: "Debut Shopify theme preview",
    sortOrder: 13,
  },
  {
    name: "Brooklyn",
    slug: "brooklyn",
    vendor: "Shopify",
    description: "Editorial free theme with strong storytelling sections.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/brooklyn",
    imageUrl: null,
    imageAlt: "Brooklyn Shopify theme preview",
    sortOrder: 14,
  },
  {
    name: "Narrative",
    slug: "narrative",
    vendor: "Shopify",
    description: "Story-first free theme built around long-form brand content.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/narrative",
    imageUrl: null,
    imageAlt: "Narrative Shopify theme preview",
    sortOrder: 15,
  },
  {
    name: "Venture",
    slug: "venture",
    vendor: "Shopify",
    description: "Outdoor and adventure aesthetic with bold imagery blocks.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/venture",
    imageUrl: null,
    imageAlt: "Venture Shopify theme preview",
    sortOrder: 16,
  },
  {
    name: "Minimal",
    slug: "minimal",
    vendor: "Shopify",
    description: "Ultra-clean free theme focused on product photography.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/minimal",
    imageUrl: null,
    imageAlt: "Minimal Shopify theme preview",
    sortOrder: 17,
  },
  {
    name: "Supply",
    slug: "supply",
    vendor: "Shopify",
    description: "Free theme optimized for multi-product inventory and B2B-style catalogs.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/supply",
    imageUrl: null,
    imageAlt: "Supply Shopify theme preview",
    sortOrder: 18,
  },
  {
    name: "Express",
    slug: "express",
    vendor: "Shopify",
    description: "Fast-setup free theme for small catalogs and pop-up shops.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/express",
    imageUrl: null,
    imageAlt: "Express Shopify theme preview",
    sortOrder: 19,
  },
  {
    name: "Craft",
    slug: "craft",
    vendor: "Shopify",
    description: "Artisan and handmade brand styling with warm typography.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/craft",
    imageUrl: null,
    imageAlt: "Craft Shopify theme preview",
    sortOrder: 20,
  },
  {
    name: "Label",
    slug: "label",
    vendor: "Shopify",
    description: "Music and entertainment merch layouts with tour-ready sections.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/label",
    imageUrl: null,
    imageAlt: "Label Shopify theme preview",
    sortOrder: 21,
  },
  {
    name: "District",
    slug: "district",
    vendor: "Shopify",
    description: "Urban streetwear styling with grid-heavy collection pages.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/district",
    imageUrl: null,
    imageAlt: "District Shopify theme preview",
    sortOrder: 22,
  },
  {
    name: "Empire",
    slug: "empire",
    vendor: "Pixel Union",
    description: "Large-catalog premium theme with advanced filtering.",
    priceType: "premium",
    priceLabel: "Premium",
    themeStoreUrl: "https://themes.shopify.com/themes/empire",
    imageUrl: null,
    imageAlt: "Empire Shopify theme preview",
    sortOrder: 23,
  },
  {
    name: "Pipeline",
    slug: "pipeline",
    vendor: "Groupthought",
    description: "Bold product storytelling for single-product and hero-SKU brands.",
    priceType: "premium",
    priceLabel: "Premium",
    themeStoreUrl: "https://themes.shopify.com/themes/pipeline",
    imageUrl: null,
    imageAlt: "Pipeline Shopify theme preview",
    sortOrder: 24,
  },
  {
    name: "Focal",
    slug: "focal",
    vendor: "Maestrooo",
    description: "Image-led premium theme for beauty and fashion lookbooks.",
    priceType: "premium",
    priceLabel: "Premium",
    themeStoreUrl: "https://themes.shopify.com/themes/focal",
    imageUrl: null,
    imageAlt: "Focal Shopify theme preview",
    sortOrder: 25,
  },
  {
    name: "Sense",
    slug: "sense",
    vendor: "Shopify",
    description: "Wellness and self-care free theme with soft palettes.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/sense",
    imageUrl: null,
    imageAlt: "Sense Shopify theme preview",
    sortOrder: 26,
  },
  {
    name: "Studio",
    slug: "studio",
    vendor: "Shopify",
    description: "Art and print-on-demand friendly free layouts.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/studio",
    imageUrl: null,
    imageAlt: "Studio Shopify theme preview",
    sortOrder: 27,
  },
  {
    name: "Ride",
    slug: "ride",
    vendor: "Shopify",
    description: "Sports and cycling brands — action imagery and specs tables.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/ride",
    imageUrl: null,
    imageAlt: "Ride Shopify theme preview",
    sortOrder: 28,
  },
  {
    name: "Taste",
    slug: "taste",
    vendor: "Shopify",
    description: "Food and beverage free theme with menu-style sections.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/taste",
    imageUrl: null,
    imageAlt: "Taste Shopify theme preview",
    sortOrder: 29,
  },
  {
    name: "Origin",
    slug: "origin",
    vendor: "Shopify",
    description: "Sustainable and organic brand storytelling on a free base.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/origin",
    imageUrl: null,
    imageAlt: "Origin Shopify theme preview",
    sortOrder: 30,
  },
  {
    name: "Broadcast",
    slug: "broadcast",
    vendor: "Invisible",
    description: "Content-rich premium theme for publishers and editorial commerce.",
    priceType: "premium",
    priceLabel: "Premium",
    themeStoreUrl: "https://themes.shopify.com/themes/broadcast",
    imageUrl: null,
    imageAlt: "Broadcast Shopify theme preview",
    sortOrder: 31,
  },
  {
    name: "Colorblock",
    slug: "colorblock",
    vendor: "Shopify",
    description: "Playful free theme with bold color blocks and campaign sections.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/colorblock",
    imageUrl: null,
    imageAlt: "Colorblock Shopify theme preview",
    sortOrder: 32,
  },
  {
    name: "Spotlight",
    slug: "spotlight",
    vendor: "Shopify",
    description: "Single-product and launch-focused free Shopify theme.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/spotlight",
    imageUrl: null,
    imageAlt: "Spotlight Shopify theme preview",
    sortOrder: 33,
  },
  {
    name: "Publisher",
    slug: "publisher",
    vendor: "Shopify",
    description: "Blog-forward free theme for content-led ecommerce.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/publisher",
    imageUrl: null,
    imageAlt: "Publisher Shopify theme preview",
    sortOrder: 34,
  },
  {
    name: "Trade",
    slug: "trade",
    vendor: "Shopify",
    description: "B2B-friendly free theme with quick order list layouts.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/trade",
    imageUrl: null,
    imageAlt: "Trade Shopify theme preview",
    sortOrder: 35,
  },
  {
    name: "Be Yours",
    slug: "be-yours",
    vendor: "RoarTheme",
    description: "Romantic and gift-focused premium layouts for seasonal campaigns.",
    priceType: "premium",
    priceLabel: "Premium",
    themeStoreUrl: "https://themes.shopify.com/themes/be-yours",
    imageUrl: null,
    imageAlt: "Be Yours Shopify theme preview",
    sortOrder: 36,
  },
  {
    name: "Showcase",
    slug: "showcase",
    vendor: "Shopify",
    description: "Product grid free theme highlighting large image tiles.",
    priceType: "free",
    priceLabel: "Free",
    themeStoreUrl: "https://themes.shopify.com/themes/showcase",
    imageUrl: null,
    imageAlt: "Showcase Shopify theme preview",
    sortOrder: 37,
  },
  {
    name: "Streamline",
    slug: "streamline",
    vendor: "Archetype Themes",
    description: "Performance-oriented premium theme for high-traffic DTC stores.",
    priceType: "premium",
    priceLabel: "Premium",
    themeStoreUrl: "https://themes.shopify.com/themes/streamline",
    imageUrl: null,
    imageAlt: "Streamline Shopify theme preview",
    sortOrder: 38,
  },
  {
    name: "Reformation",
    slug: "reformation",
    vendor: "Fuel Themes",
    description: "Modern premium theme with strong typography and conversion blocks.",
    priceType: "premium",
    priceLabel: "Premium",
    themeStoreUrl: "https://themes.shopify.com/themes/reformation",
    imageUrl: null,
    imageAlt: "Reformation Shopify theme preview",
    sortOrder: 39,
  },
];

const featuredAsSeed: ThemeCatalogSeed[] = featuredThemes.map((t, i) => ({
  name: t.name,
  slug: t.slug,
  vendor: t.vendor,
  description: t.description,
  priceType: t.priceType,
  priceLabel: t.priceLabel,
  themeStoreUrl: t.themeStoreUrl,
  imageUrl: t.imageUrl,
  imageAlt: t.imageAlt,
  sortOrder: i + 1,
}));

const bySlug = new Map<string, ThemeCatalogSeed>();
for (const t of [...featuredAsSeed, ...extraThemes]) {
  bySlug.set(t.slug, t);
}

export const themeCatalogSeed: ThemeCatalogSeed[] = [...bySlug.values()].sort(
  (a, b) => a.sortOrder - b.sortOrder
);

export function getThemeCatalogSeedBySlug(
  slug: string
): ThemeCatalogSeed | undefined {
  return themeCatalogSeed.find((t) => t.slug === slug);
}

export function catalogSeedToFeaturedTheme(seed: ThemeCatalogSeed) {
  return {
    name: seed.name,
    slug: seed.slug,
    vendor: seed.vendor,
    description: seed.description,
    metaDescription: seed.description,
    priceType: seed.priceType,
    priceLabel: seed.priceLabel,
    priceDisplay: seed.priceLabel,
    features: [] as string[],
    overview: [seed.description],
    exampleStoresToScan: [],
    themeStoreUrl: seed.themeStoreUrl,
    imageUrl: seed.imageUrl ?? "",
    imageAlt: seed.imageAlt,
  };
}
